add pure-push hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,11 +1,18 @@
 #!/bin/sh
 
 # Makefile の format コマンドを実行
-make format
-make lint
-make test
+if ! make format; then
+  echo "Formatting failed, pre-commit hook aborting commit."
+  exit 1
+fi
 
-# 変更されたファイルをステージングに追加
-git add $(git diff --cached --name-only --diff-filter=d | grep '\.py$')
+# Makefile の lint コマンドを実行
+if ! make lint; then
+  echo "Linting failed, pre-commit hook aborting commit."
+  exit 1
+fi
+
+# 変更された Python ファイルをステージングに追加
+git diff --cached --name-only --diff-filter=d | grep '\.py$' | xargs git add
 
 exit 0
